/**
 * Forward-only migration runner. Reads `world_meta.schema_version` (or
 * detects an empty database on first boot), replays every migration
 * with `idx > current_version`, and bumps `schema_version` to the
 * latest migration's `idx + 1` in a single transaction.
 *
 * The migrations themselves live in `src/db/migrations/*.sql` and are
 * generated by `pnpm drizzle:gen`. Their journal at
 * `src/db/migrations/meta/_journal.json` is the source of truth for
 * order and tags — we read it via `import.meta.glob` (Vite) or a
 * direct `import` shim in tests.
 *
 * Why not use drizzle's built-in `migrate()`? Two reasons:
 *  1. Spec §8.3 wants schema_version stored on `world_meta` (a real
 *     row, not a `__drizzle_migrations` table). End-of-run journal +
 *     debugger view both surface schema_version naturally that way.
 *  2. Drizzle's web migrator expects a Node-only `fs` lookup of the
 *     `.sql` files; bundling for sql.js + capacitor-community/sqlite
 *     means the migrations come pre-imported as strings.
 *
 * See tests/db/migrate.test.ts for the round-trip on an in-memory
 * sql.js Database.
 */

export interface MigrationRunnerInput {
	/** Returns scalar values from a single-row query. Used to read the
	 *  current `world_meta.schema_version`. Implementations must return
	 *  `null` if the table doesn't exist yet (fresh DB). */
	getCurrentVersion(): number | null;
	/** Run a single SQL block atomically. Multiple statements in the same
	 *  string MUST commit together; if any fails, the implementation
	 *  must roll back. Drizzle proxies + sql.js `db.exec` already do
	 *  this by default. */
	exec(sql: string): void;
}

export interface MigrationEntry {
	idx: number;
	tag: string;
	sql: string;
}

export interface MigrationRunResult {
	/** Number of migrations actually applied this run. 0 = up-to-date. */
	applied: number;
	/** New schema_version recorded on world_meta after the run. */
	newVersion: number;
	/** Tags of the migrations that ran (in apply order). */
	appliedTags: string[];
}

/**
 * Apply every pending migration. Idempotent: calling twice with no new
 * migrations is a no-op. Throws if `migrations` are out of order or if
 * any individual migration fails (the implementation rolls back via
 * the adapter's transaction semantics).
 */
export function runMigrations(
	input: MigrationRunnerInput,
	migrations: readonly MigrationEntry[],
): MigrationRunResult {
	assertSorted(migrations);

	const current = input.getCurrentVersion();
	const startIdx = current ?? -1;
	const appliedTags: string[] = [];

	for (const m of migrations) {
		if (m.idx <= startIdx) continue;
		input.exec(m.sql);
		appliedTags.push(m.tag);
	}

	const lastIdx = migrations.length === 0 ? startIdx : (migrations.at(-1)?.idx ?? startIdx);
	const newVersion = Math.max(startIdx, lastIdx);

	if (appliedTags.length > 0) {
		// world_meta may not exist before the first migration; after, it does.
		// Schema version is the *latest applied migration idx + 1* so a fresh
		// DB at version 0 means "0000_initial has been applied and nothing
		// newer is pending." This matches the conventional drizzle journal
		// semantics where idx is 0-based.
		input.exec(
			`INSERT OR IGNORE INTO world_meta (id, seed) VALUES (1, '');\n` +
				`UPDATE world_meta SET schema_version = ${newVersion + 1}, updated_at = (unixepoch() * 1000) WHERE id = 1;`,
		);
	}

	return {
		applied: appliedTags.length,
		newVersion: newVersion + 1,
		appliedTags,
	};
}

function assertSorted(migrations: readonly MigrationEntry[]): void {
	for (let i = 1; i < migrations.length; i++) {
		const prev = migrations[i - 1];
		const cur = migrations[i];
		if (!prev || !cur) continue;
		if (cur.idx <= prev.idx) {
			throw new Error(
				`migrations out of order: ${prev.tag}(idx=${prev.idx}) followed by ${cur.tag}(idx=${cur.idx})`,
			);
		}
	}
}
