/**
 * Typed loader for `public/assets/models/manifest.json`. Manifest is fetched
 * once at module init via top-level await; subsequent imports get the
 * already-resolved object.
 *
 * Generated by `scripts/convert-references.py`. Schema is locked in spec
 * §3.3.
 */

export type ManifestEntry = {
	path: string;
	scale: number;
	anchor: [number, number, number];
	footprintCells: [number, number, number];
	tags: string[];
	sourceHash: string;
};

export type Manifest = {
	version: number;
	characters: Record<string, ManifestEntry>;
	props: Record<string, ManifestEntry>;
	traps: Record<string, ManifestEntry>;
};

let pending: Promise<Manifest> | null = null;

/**
 * Asynchronously load the manifest. Caches the in-flight promise (not just
 * the resolved value) so concurrent callers — including React 18 StrictMode
 * double-invokes — share a single network fetch.
 *
 * In Vitest browser tests Vite serves `public/` at the root, so the path
 * resolves identically to production.
 */
export function loadManifest(): Promise<Manifest> {
	if (pending) return pending;
	pending = (async () => {
		const r = await fetch('/assets/models/manifest.json');
		if (!r.ok) throw new Error(`Failed to load manifest: ${r.status}`);
		return (await r.json()) as Manifest;
	})();
	// Drop the cached promise on failure so a retry succeeds without page reload.
	pending.catch(() => {
		pending = null;
	});
	return pending;
}

/** Lookup a slug, throwing if absent. */
export function getEntry(
	manifest: Manifest,
	group: keyof Pick<Manifest, 'characters' | 'props' | 'traps'>,
	slug: string,
): ManifestEntry {
	const entry = manifest[group][slug];
	if (!entry) throw new Error(`Manifest missing: ${group}/${slug}`);
	return entry;
}
