/**
 * Typed loader for `public/assets/models/manifest.json`. Manifest is fetched
 * once at module init via top-level await; subsequent imports get the
 * already-resolved object.
 *
 * Generated by `scripts/convert-references.py`. Schema is locked in spec
 * §3.3.
 */

export type ManifestEntry = {
	path: string;
	scale: number;
	anchor: [number, number, number];
	footprintCells: [number, number, number];
	tags: string[];
	sourceHash: string;
};

export type Manifest = {
	version: number;
	characters: Record<string, ManifestEntry>;
	props: Record<string, ManifestEntry>;
	traps: Record<string, ManifestEntry>;
};

let cached: Manifest | null = null;

/**
 * Asynchronously load the manifest. Cached after first call.
 *
 * In Vitest browser tests Vite serves `public/` at the root, so the path
 * resolves identically to production.
 */
export async function loadManifest(): Promise<Manifest> {
	if (cached) return cached;
	const r = await fetch('/assets/models/manifest.json');
	if (!r.ok) throw new Error(`Failed to load manifest: ${r.status}`);
	const m = (await r.json()) as Manifest;
	cached = m;
	return m;
}

/** Lookup a slug, throwing if absent. */
export function getEntry(
	manifest: Manifest,
	group: keyof Pick<Manifest, 'characters' | 'props' | 'traps'>,
	slug: string,
): ManifestEntry {
	const entry = manifest[group][slug];
	if (!entry) throw new Error(`Manifest missing: ${group}/${slug}`);
	return entry;
}
